services:
  jekyll:
    image: ruby:3.1
    working_dir: /srv/jekyll
    command: bash -c "bundle install && bundle exec jekyll serve --watch --incremental --future --host 0.0.0.0"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll:Z
      - bundle:/usr/local/bundle

volumes:
  bundle:
