<p>
The Open Build Service (OBS) is a generic system to build and distribute binary packages from sources
in an automatic, consistent and reproducible way. You can release packages as well as updates, add-ons,
appliances and entire distributions for a wide range of operating systems and hardware architectures.
</p>
<p>
It is developed by a talented <a href="https://openbuildservice.org/team/">team</a> of developers as
Free Software and is used by many Free and Open Source software projects, companies and researchers.
Including but not limited to <a href="https://www.suse.com">SUSE</a> the original provider of the
enterprise Linux distribution, the <a href="https://www.tizen.org/">Tizen</a> standards-based software
platform supported by leading mobile operators and <a href="https://owncloud.org/">ownCloud</a> your
secure enterprise file sync and share.
</p>
<p>

</p>
