<div class="row">
	<div class="four columns">
		<div class="row">
			<div class="twelve columns author-pic">
				<div class="panel radius">
				<img class="displayed" src="/images/team/adrian.jpg">
				</div>
			</div>
		</div>
	</div>
	<div class="eight columns">
		<div class="row">
			<div class="twelve columns author-title">
				<h4>Adrian Schröter</h4>
				<h5>Admin, Hacker, Project Manager, here since day one</h5>
			</div>
			<div class="twelve columns author-bio">
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc in purus id tellus hendrerit
					tempus eget eu mauris. Fusce tincidunt massa id libero varius ultrices. In non ligula felis.
					Nullam eu egestas tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices 
					posuere cubilia Curae; Nulla condimentum interdum semper. Pellentesque sed interdum neque. 
					Nulla rhoncus faucibus orci sed tristique. Aliquam ac augue augue.
				</p>
			</div>
			<div class="twelve columns author-links">
				<ul class="link-list">
				<li><a href="mailto:adrian@suse.de"><img src="/images/icons/email.png" title="Email Adrian"></a></li>
				<li><a href="http://www.adrian-schroeter.de/"><img src="/images/icons/rss.png" title="Adrians Blog"></a></li>
				<li><a href="http://github.com/adrianschroeter"><img src="/images/icons/github.png" title="Adrian on Github"></a></li>
				<li><a href="http://twitter.com/AdrianSchroeter"><img src="/images/icons/twitter.png" title="Adrian on Twitter"></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
