<div class="row">
	<div class="four columns">
		<div class="row">
			<div class="twelve columns author-pic">
				<div class="panel radius">
				<img class="displayed" src="/images/team/henne.jpg">
				</div>
			</div>
		</div>
	</div>
	<div class="eight columns">
		<div class="row">
			<div class="twelve columns author-title">
				<h4>Henne Vogelsang</h4>
				<h5>Web dude, Marketing fumbler, freshman</h5>
			</div>
			<div class="twelve columns author-bio">
				<p>
					Henne is the newest addition to the OBS team. Previously fully engaged in the openSUSE project
					as founding and board member, admin and infrastructure hacker, marketing fumbler and packager he brings
					the experience of building an open source project from the ground up. Henne can also draw upon a 10+
					year career working for SUSE as package maintainer and project manager.
				</p>
				<p>
				  You will see him beefing up the OBS web client, project resources, documentation and promotion when he's not
				  out viciously supporting his hometown football club S.V. Werder Bremen, hiking the alps or exploring the breweries
				  of the franconian switzerland.
				</p>
			</div>
			<div class="twelve columns author-links">
				<ul class="link-list">
				<li><a href="mailto:hvogel@opensuse.org"><img src="/images/icons/email.png" title="Email Henne"></a></li>
				<li><a href="http://www.hennevogel.de/"><img src="/images/icons/rss.png" title="Henne's Blog"></a></li>
				<li><a href="http://github.com/hennevogel"><img src="/images/icons/github.png" title="Henne on Github"></a></li>
				<li><a href="http://twitter.com/henne"><img src="/images/icons/twitter.png" title="Henne on Twitter"></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
