<div class="row">
	<div class="four columns">
		<div class="row">
			<div class="twelve columns author-pic">
				<div class="panel radius">
				<img class="displayed" src="/images/team/henne.jpg">
				</div>
			</div>
		</div>
	</div>
	<div class="eight columns">
		<div class="row">
			<div class="twelve columns author-title">
				<h4>Henne Vogelsang</h4>
				<h5>Web dude, Marketing fumbler, freshman</h5>
			</div>
			<div class="twelve columns author-bio">
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc in purus id tellus hendrerit
					tempus eget eu mauris. Fusce tincidunt massa id libero varius ultrices. In non ligula felis.
					Nullam eu egestas tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices 
					posuere cubilia Curae; Nulla condimentum interdum semper. Pellentesque sed interdum neque. 
					Nulla rhoncus faucibus orci sed tristique. Aliquam ac augue augue.
				</p>
			</div>
			<div class="twelve columns author-links">
				<ul class="link-list">
				<li><a href="mailto:hvogel@opensuse.org"><img src="/images/icons/email.png" title="Email Henne"></a></li>
				<li><a href="http://www.hennevogel.de/"><img src="/images/icons/rss.png" title="Henne's Blog"></a></li>
				<li><a href="http://github.com/hennevogel"><img src="/images/icons/github.png" title="Henne on Github"></a></li>
				<li><a href="http://twitter.com/henne"><img src="/images/icons/twitter.png" title="Henne on Twitter"></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
