<div class="row">
	<div class="four columns">
		<div class="row">
			<div class="twelve columns author-pic">
				<div class="panel radius">
				<img class="displayed" src="/images/team/marcus.jpg">
				</div>
			</div>
		</div>
	</div>
	<div class="eight columns">
		<div class="row">
			<div class="twelve columns author-title">
				<h4>Marcus Hüwe</h4>
				<h5>Commandline Client Hacker, Youngie  </h5>
			</div>
			<div class="twelve columns author-bio">
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc in purus id tellus hendrerit
					tempus eget eu mauris. Fusce tincidunt massa id libero varius ultrices. In non ligula felis.
					Nullam eu egestas tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices 
					posuere cubilia Curae; Nulla condimentum interdum semper. Pellentesque sed interdum neque. 
					Nulla rhoncus faucibus orci sed tristique. Aliquam ac augue augue.
				</p>
			</div>
			<div class="twelve columns author-links">
				<ul class="link-list">
				<li><a href="mailto:suse-tux@gmx.de"><img src="/images/icons/email.png" title="Email Marcus"></a></li>
				<li><a href="http://lizards.opensuse.org/author/marcus_h/"><img src="/images/icons/rss.png" title="Marcus Blog"></a></li>
				<li><a href="http://github.com/marcus-h"><img src="/images/icons/github.png" title="Marcus on Github"></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
