<div class="row">
	<div class="four columns">
		<div class="row">
			<div class="twelve columns author-pic">
				<div class="panel radius">
				<img class="displayed" src="/images/team/mls.jpg">
				</div>
			</div>
		</div>
	</div>
	<div class="eight columns">
		<div class="row">
			<div class="twelve columns author-title">
				<h4>Michael Schröder</h4>
				<h5>Backend Hacker, Project Manager, Superbrain</h5>
			</div>
			<div class="twelve columns author-bio">
				<p>
					Michael, a Ph.D. in Computer Science from the famous University of Erlangen-Nuremberg, is another FOSS
					old-timer in the team. Most hackers probably know him as one of the GNU screen maintainers,
					perl guru and dependency solver expert.
					Even before the inauguration of the Open Build Service Michael worked on the SUSE internal OBS predecessor
					<em>autobuild</em> which means he brings more than 10 years of experience in developing build system backends
					to the table! At SUSE Michael shares the role of project manager for the SUSE and openSUSE build infrastructure
					with Adrian.
				</p>
				<p>
				  Apart from expanding the OBS backend with all kinds of cool features and taking care of the reference server
				  backend, cooking good food and gaming make Michael a happy man.
				</p>
			</div>
			<div class="twelve columns author-links">
				<ul class="link-list">
				<li><a href="mailto:mls@suse.com"><img src="/images/icons/email.png" title="Email Michael"></a></li>
				<li><a href="http://github.com/mlschroe"><img src="/images/icons/github.png" title="Michael on Github"></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
