<p>
The reference server <a href="http://build.opensuse.org/">http://build.opensuse.org</a> is available for
all open source developers to build packages for the most popular distributions including openSUSE, Debian,
Fedora, Ubuntu, Red Hat Enterprise Linux, SUSE Linux Enterprise. It is also used to build the
<a href="http://www.opensuse.org" title="openSUSE Linux">openSUSE</a> distribution.
</p>
