<p>
The reference server <a href="http://build.opensuse.org/" target="_blank" title="Reference Server">build.opensuse.org</a> is available for
all open source developers to build packages for the most popular distributions including openSUSE, Debian,
Fedora, Ubuntu, Arch, Red Hat Enterprise Linux and SUSE Linux Enterprise. It is also used to build, release
and maintain the <a href="http://www.opensuse.org" title="openSUSE Linux" target="_blank">openSUSE</a> distribution.
</p>
